Homework3
jurasup/homeworks-java.tat pull request #16
Opened 2016-10-09 22:00 UTC by jurasup

2016-10-09 22:04 UTC, jurasup commented
Пулл-реквест получился корявым. Когда-нибудь я научусь нормально работать с ГитХабом...

2016-10-10 12:19 UTC, AlexanderSoroka requested changes

2016-10-10 12:19 UTC, AlexanderSoroka commented on TAT.homework2/src/NumberOfWordsCheck.java
> +    if (numberOfWords <= 5) {
make 5 as class parameter or at least const

2016-10-10 12:19 UTC, AlexanderSoroka commented on TAT.homework2/src/StringMonitor.java
> +    for (Check check : checks) {
Extract it to separate class

2016-10-10 13:54 UTC, closed without merging